### ISSUE TITLE
サービスの方向性（1stステップ）

### ISSUE THREAD

**Issue by mosuke5** [atp-stat/atp-stat#1]
【構想】
選手の対戦成績を様々な角度の分析結果が閲覧できる。
おもに下記の対戦を閲覧できる。
（ATPのサイトでも数字は見ることができるが、実際にだれに負け、だれに勝ったかはわからない。）
- 対トップ10との対戦
- 自分よりランクが上への勝利
- 自分よりランクが下への敗北

【ページ構成】
- トップ
  - 選手の検索ができる
- 選手ページ
  - 独自指標での対戦成績分析がみれる

**Comment by ioroioroi** [comment]
![ss](https://cloud.githubusercontent.com/assets/17192499/14065910/00b6cf76-f477-11e5-8bee-141df11168b2.png)

選手ページに、選手画像の代わりに選手のYoutube動画を掲載、とかはいかがでしょうか？

**Comment by mosuke5** [comment]
そうだね何らかの形で、他サービスと連携したいよね。
選手の特徴的なシーンだけ動画で勝手に再生されていればかっこいいな…

**Comment by mosuke5** [comment]
対戦成績に特化し、当面は対戦成績の分析やそのグラフ化などに注力するで一旦クローズ
