### ISSUE TITLE
ランキングが不正値の場合

### ISSUE THREAD

**Issue by mosuke5** [atp-stat/atp-stat#2]
ランキングが0とか-であることがまれにある。
http://www.atpworldtour.com/en/players/yuichi-sugita/se73/player-activity

この場合DBに0として格納されている・・・

**Comment by h3pei** [comment]
+1

**Comment by mosuke5** [comment]
AtpScraper側で対応するようにする

**Comment by ioroioroi** [comment]
ランキング0現象、試合の種類や選手によるとかでなく
ATP側もうまく情報を取得できてないだけのように見えますね...
特に中国・上海の試合だとランキング取得できてなさそうな

**Comment by mosuke5** [comment]
改善しました。
